[2024-03-09T03:00:14.502+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_api_dag.create_weather_table scheduled__2024-03-09T02:00:00+00:00 [queued]>
[2024-03-09T03:00:14.509+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_api_dag.create_weather_table scheduled__2024-03-09T02:00:00+00:00 [queued]>
[2024-03-09T03:00:14.509+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-03-09T03:00:14.526+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): create_weather_table> on 2024-03-09 02:00:00+00:00
[2024-03-09T03:00:14.537+0000] {standard_task_runner.py:60} INFO - Started process 3227 to run task
[2024-03-09T03:00:14.540+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'weather_api_dag', 'create_weather_table', 'scheduled__2024-03-09T02:00:00+00:00', '--job-id', '460', '--raw', '--subdir', 'DAGS_FOLDER/weather_api__dag.py', '--cfg-path', '/tmp/tmp51jwgwe1']
[2024-03-09T03:00:14.541+0000] {standard_task_runner.py:88} INFO - Job 460: Subtask create_weather_table
[2024-03-09T03:00:14.588+0000] {task_command.py:423} INFO - Running <TaskInstance: weather_api_dag.create_weather_table scheduled__2024-03-09T02:00:00+00:00 [running]> on host 70ec329f3d65
[2024-03-09T03:00:14.670+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='kan@odds.team' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_api_dag' AIRFLOW_CTX_TASK_ID='create_weather_table' AIRFLOW_CTX_EXECUTION_DATE='2024-03-09T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-09T02:00:00+00:00'
[2024-03-09T03:00:14.672+0000] {warnings.py:109} WARNING - /opt/***/dags/weather_api__dag.py:67: AirflowProviderDeprecationWarning: The "schema" arg has been renamed to "database" as it contained the database name.Please use "database" to set the database name.
  pg_hook = PostgresHook(

[2024-03-09T03:00:14.679+0000] {base.py:83} INFO - Using connection ID 'my_***_conn' for task execution.
[2024-03-09T03:00:14.686+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-03-09T03:00:14.695+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=weather_api_dag, task_id=create_weather_table, execution_date=20240309T020000, start_date=20240309T030014, end_date=20240309T030014
[2024-03-09T03:00:14.753+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-09T03:00:14.779+0000] {taskinstance.py:3281} INFO - 1 downstream tasks scheduled from follow-on schedule check
