[2024-03-09T05:00:12.514+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_api_dag.create_weather_table scheduled__2024-03-09T04:00:00+00:00 [queued]>
[2024-03-09T05:00:12.523+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_api_dag.create_weather_table scheduled__2024-03-09T04:00:00+00:00 [queued]>
[2024-03-09T05:00:12.524+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-03-09T05:00:12.544+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): create_weather_table> on 2024-03-09 04:00:00+00:00
[2024-03-09T05:00:12.560+0000] {standard_task_runner.py:60} INFO - Started process 14128 to run task
[2024-03-09T05:00:12.567+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'weather_api_dag', 'create_weather_table', 'scheduled__2024-03-09T04:00:00+00:00', '--job-id', '468', '--raw', '--subdir', 'DAGS_FOLDER/weather_api__dag.py', '--cfg-path', '/tmp/tmpcaoz4m4y']
[2024-03-09T05:00:12.568+0000] {standard_task_runner.py:88} INFO - Job 468: Subtask create_weather_table
[2024-03-09T05:00:12.633+0000] {task_command.py:423} INFO - Running <TaskInstance: weather_api_dag.create_weather_table scheduled__2024-03-09T04:00:00+00:00 [running]> on host 70ec329f3d65
[2024-03-09T05:00:12.788+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='kan@odds.team' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_api_dag' AIRFLOW_CTX_TASK_ID='create_weather_table' AIRFLOW_CTX_EXECUTION_DATE='2024-03-09T04:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-09T04:00:00+00:00'
[2024-03-09T05:00:12.789+0000] {warnings.py:109} WARNING - /opt/***/dags/weather_api__dag.py:67: AirflowProviderDeprecationWarning: The "schema" arg has been renamed to "database" as it contained the database name.Please use "database" to set the database name.
  pg_hook = PostgresHook(

[2024-03-09T05:00:12.801+0000] {base.py:83} INFO - Using connection ID 'my_***_conn' for task execution.
[2024-03-09T05:00:12.813+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-03-09T05:00:12.824+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=weather_api_dag, task_id=create_weather_table, execution_date=20240309T040000, start_date=20240309T050012, end_date=20240309T050012
[2024-03-09T05:00:12.859+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-09T05:00:12.890+0000] {taskinstance.py:3281} INFO - 1 downstream tasks scheduled from follow-on schedule check
