[2024-03-16T02:58:46.228+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dbt_dag.my_model_run scheduled__2024-03-15T00:00:00+00:00 [queued]>
[2024-03-16T02:58:46.237+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dbt_dag.my_model_run scheduled__2024-03-15T00:00:00+00:00 [queued]>
[2024-03-16T02:58:46.238+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-03-16T02:58:46.259+0000] {taskinstance.py:2192} INFO - Executing <Task(DbtRunLocalOperator): my_model_run> on 2024-03-15 00:00:00+00:00
[2024-03-16T02:58:46.268+0000] {standard_task_runner.py:60} INFO - Started process 908 to run task
[2024-03-16T02:58:46.275+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'weather_dbt_dag', 'my_model_run', 'scheduled__2024-03-15T00:00:00+00:00', '--job-id', '480', '--raw', '--subdir', 'DAGS_FOLDER/weather_dbt_dag.py', '--cfg-path', '/tmp/tmpwkaz5sca']
[2024-03-16T02:58:46.278+0000] {standard_task_runner.py:88} INFO - Job 480: Subtask my_model_run
[2024-03-16T02:58:46.345+0000] {task_command.py:423} INFO - Running <TaskInstance: weather_dbt_dag.my_model_run scheduled__2024-03-15T00:00:00+00:00 [running]> on host a084c6a0d68a
[2024-03-16T02:58:46.453+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_dbt_dag' AIRFLOW_CTX_TASK_ID='my_model_run' AIRFLOW_CTX_EXECUTION_DATE='2024-03-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-15T00:00:00+00:00'
[2024-03-16T02:58:46.454+0000] {local.py:202} INFO - Cloning project to writable temp directory /tmp/tmpgszw9q_5 from /opt/airflow/dbt/weather
[2024-03-16T02:58:46.469+0000] {base.py:83} INFO - Using connection ID 'my_***_conn' for task execution.
[2024-03-16T02:58:46.469+0000] {base.py:171} INFO - Using real values for profile weather
[2024-03-16T02:58:46.471+0000] {config.py:278} INFO - Creating temporary profiles.yml at /tmp/tmphho9jw21/profiles.yml with the following contents:
weather:
    outputs:
        dev:
            dbname: ***
            host: mydb
            password: '{{ env_var(''COSMOS_CONN_POSTGRES_PASSWORD'') }}'
            port: 5432
            schema: dbt_gai
            type: ***
            user: ***
    target: dev

[2024-03-16T02:58:46.473+0000] {local.py:235} INFO - Trying to run the command:
 ['/home/***/.local/bin/dbt', 'run', '--models', 'my_model', '--profiles-dir', '/tmp/tmphho9jw21', '--profile', 'weather', '--target', 'dev']
From /tmp/tmpgszw9q_5
[2024-03-16T02:58:46.474+0000] {local.py:236} INFO - Using environment variables keys: dict_keys(['AIRFLOW_CTX_DAG_OWNER', 'AIRFLOW_CTX_DAG_ID', 'AIRFLOW_CTX_TASK_ID', 'AIRFLOW_CTX_EXECUTION_DATE', 'AIRFLOW_CTX_TRY_NUMBER', 'AIRFLOW_CTX_DAG_RUN_ID', 'COSMOS_CONN_POSTGRES_PASSWORD'])
[2024-03-16T02:58:46.475+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-03-16T02:58:46.478+0000] {subprocess.py:73} INFO - Running command: ['/home/***/.local/bin/dbt', 'run', '--models', 'my_model', '--profiles-dir', '/tmp/tmphho9jw21', '--profile', 'weather', '--target', 'dev']
[2024-03-16T02:58:46.502+0000] {subprocess.py:84} INFO - Command output:
[2024-03-16T02:58:50.893+0000] {subprocess.py:94} INFO - [0m02:58:50  Running with dbt=1.7.9
[2024-03-16T02:58:51.531+0000] {subprocess.py:94} INFO - [0m02:58:51  Registered adapter: ***=1.7.9
[2024-03-16T02:58:51.548+0000] {subprocess.py:94} INFO - [0m02:58:51  Unable to do partial parsing because saved manifest not found. Starting full parse.
[2024-03-16T02:58:53.825+0000] {subprocess.py:94} INFO - [0m02:58:53  Found 5 models, 9 tests, 1 source, 0 exposures, 0 metrics, 401 macros, 0 groups, 0 semantic models
[2024-03-16T02:58:53.829+0000] {subprocess.py:94} INFO - [0m02:58:53
[2024-03-16T02:58:54.279+0000] {subprocess.py:94} INFO - [0m02:58:54  Concurrency: 1 threads (target='dev')
[2024-03-16T02:58:54.281+0000] {subprocess.py:94} INFO - [0m02:58:54
[2024-03-16T02:58:54.293+0000] {subprocess.py:94} INFO - [0m02:58:54  1 of 1 START sql view model dbt_gai.my_model ................................... [RUN]
[2024-03-16T02:58:54.499+0000] {subprocess.py:94} INFO - [0m02:58:54  1 of 1 OK created sql view model dbt_gai.my_model .............................. [[32mCREATE VIEW[0m in 0.20s]
[2024-03-16T02:58:54.514+0000] {subprocess.py:94} INFO - [0m02:58:54
[2024-03-16T02:58:54.515+0000] {subprocess.py:94} INFO - [0m02:58:54  Finished running 1 view model in 0 hours 0 minutes and 0.68 seconds (0.68s).
[2024-03-16T02:58:54.534+0000] {subprocess.py:94} INFO - [0m02:58:54
[2024-03-16T02:58:54.537+0000] {subprocess.py:94} INFO - [0m02:58:54  [32mCompleted successfully[0m
[2024-03-16T02:58:54.544+0000] {subprocess.py:94} INFO - [0m02:58:54
[2024-03-16T02:58:54.545+0000] {subprocess.py:94} INFO - [0m02:58:54  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-03-16T02:58:55.941+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-03-16T02:58:55.953+0000] {local.py:138} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v11.json is above dbt-ol supported version 7. This might cause errors.
[2024-03-16T02:58:55.958+0000] {local.py:252} INFO - Inlets: []
[2024-03-16T02:58:55.958+0000] {local.py:253} INFO - Outlets: [Dataset(uri='postgres://mydb:5432/postgres.dbt_gai.my_model', extra=None)]
[2024-03-16T02:58:55.959+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-03-16T02:58:55.986+0000] {dag.py:3820} INFO - Setting next_dagrun for weather_dbt_dag to 2024-03-16T00:00:00+00:00, run_after=2024-03-17T00:00:00+00:00
[2024-03-16T02:58:56.021+0000] {local.py:371} INFO - [0m02:58:54  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-03-16T02:58:56.023+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/models/baseoperator.py:1476 RemovedInAirflow3Warning: Passing 'execution_date' to 'TaskInstance.xcom_push()' is deprecated.
[2024-03-16T02:58:56.050+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=weather_dbt_dag, task_id=my_model_run, execution_date=20240315T000000, start_date=20240316T025846, end_date=20240316T025856
[2024-03-16T02:58:56.101+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-16T02:58:56.114+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
