[2024-03-16T03:04:59.162+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dbt_dag.my_second_dbt_model.run scheduled__2024-03-15T00:00:00+00:00 [queued]>
[2024-03-16T03:04:59.171+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dbt_dag.my_second_dbt_model.run scheduled__2024-03-15T00:00:00+00:00 [queued]>
[2024-03-16T03:04:59.172+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-03-16T03:04:59.189+0000] {taskinstance.py:2192} INFO - Executing <Task(DbtRunLocalOperator): my_second_dbt_model.run> on 2024-03-15 00:00:00+00:00
[2024-03-16T03:04:59.197+0000] {standard_task_runner.py:60} INFO - Started process 1756 to run task
[2024-03-16T03:04:59.221+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'weather_dbt_dag', 'my_second_dbt_model.run', 'scheduled__2024-03-15T00:00:00+00:00', '--job-id', '489', '--raw', '--subdir', 'DAGS_FOLDER/weather_dbt_dag.py', '--cfg-path', '/tmp/tmpzfmfyd3i']
[2024-03-16T03:04:59.224+0000] {standard_task_runner.py:88} INFO - Job 489: Subtask my_second_dbt_model.run
[2024-03-16T03:04:59.317+0000] {task_command.py:423} INFO - Running <TaskInstance: weather_dbt_dag.my_second_dbt_model.run scheduled__2024-03-15T00:00:00+00:00 [running]> on host a084c6a0d68a
[2024-03-16T03:04:59.446+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_dbt_dag' AIRFLOW_CTX_TASK_ID='my_second_dbt_model.run' AIRFLOW_CTX_EXECUTION_DATE='2024-03-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-15T00:00:00+00:00'
[2024-03-16T03:04:59.447+0000] {local.py:202} INFO - Cloning project to writable temp directory /tmp/tmp0s2elr4h from /opt/airflow/dbt/weather
[2024-03-16T03:04:59.459+0000] {base.py:83} INFO - Using connection ID 'my_***_conn' for task execution.
[2024-03-16T03:04:59.460+0000] {base.py:171} INFO - Using real values for profile weather
[2024-03-16T03:04:59.462+0000] {config.py:278} INFO - Creating temporary profiles.yml at /tmp/tmpfn_8n0yn/profiles.yml with the following contents:
weather:
    outputs:
        dev:
            dbname: ***
            host: mydb
            password: '{{ env_var(''COSMOS_CONN_POSTGRES_PASSWORD'') }}'
            port: 5432
            schema: dbt_gai
            type: ***
            user: ***
    target: dev

[2024-03-16T03:04:59.463+0000] {local.py:235} INFO - Trying to run the command:
 ['/home/***/.local/bin/dbt', 'run', '--models', 'my_second_dbt_model', '--profiles-dir', '/tmp/tmpfn_8n0yn', '--profile', 'weather', '--target', 'dev']
From /tmp/tmp0s2elr4h
[2024-03-16T03:04:59.464+0000] {local.py:236} INFO - Using environment variables keys: dict_keys(['AIRFLOW_CTX_DAG_OWNER', 'AIRFLOW_CTX_DAG_ID', 'AIRFLOW_CTX_TASK_ID', 'AIRFLOW_CTX_EXECUTION_DATE', 'AIRFLOW_CTX_TRY_NUMBER', 'AIRFLOW_CTX_DAG_RUN_ID', 'COSMOS_CONN_POSTGRES_PASSWORD'])
[2024-03-16T03:04:59.465+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-03-16T03:04:59.465+0000] {subprocess.py:73} INFO - Running command: ['/home/***/.local/bin/dbt', 'run', '--models', 'my_second_dbt_model', '--profiles-dir', '/tmp/tmpfn_8n0yn', '--profile', 'weather', '--target', 'dev']
[2024-03-16T03:04:59.480+0000] {subprocess.py:84} INFO - Command output:
[2024-03-16T03:05:02.213+0000] {subprocess.py:94} INFO - [0m03:05:02  Running with dbt=1.7.9
[2024-03-16T03:05:02.649+0000] {subprocess.py:94} INFO - [0m03:05:02  Registered adapter: ***=1.7.9
[2024-03-16T03:05:02.660+0000] {subprocess.py:94} INFO - [0m03:05:02  Unable to do partial parsing because saved manifest not found. Starting full parse.
[2024-03-16T03:05:04.148+0000] {subprocess.py:94} INFO - [0m03:05:04  Found 5 models, 9 tests, 1 source, 0 exposures, 0 metrics, 401 macros, 0 groups, 0 semantic models
[2024-03-16T03:05:04.150+0000] {subprocess.py:94} INFO - [0m03:05:04
[2024-03-16T03:05:04.228+0000] {subprocess.py:94} INFO - [0m03:05:04  Concurrency: 1 threads (target='dev')
[2024-03-16T03:05:04.229+0000] {subprocess.py:94} INFO - [0m03:05:04
[2024-03-16T03:05:04.242+0000] {subprocess.py:94} INFO - [0m03:05:04  1 of 1 START sql view model dbt_gai.my_second_dbt_model ........................ [RUN]
[2024-03-16T03:05:04.395+0000] {subprocess.py:94} INFO - [0m03:05:04  1 of 1 OK created sql view model dbt_gai.my_second_dbt_model ................... [[32mCREATE VIEW[0m in 0.15s]
[2024-03-16T03:05:04.409+0000] {subprocess.py:94} INFO - [0m03:05:04
[2024-03-16T03:05:04.410+0000] {subprocess.py:94} INFO - [0m03:05:04  Finished running 1 view model in 0 hours 0 minutes and 0.26 seconds (0.26s).
[2024-03-16T03:05:04.423+0000] {subprocess.py:94} INFO - [0m03:05:04
[2024-03-16T03:05:04.423+0000] {subprocess.py:94} INFO - [0m03:05:04  [32mCompleted successfully[0m
[2024-03-16T03:05:04.424+0000] {subprocess.py:94} INFO - [0m03:05:04
[2024-03-16T03:05:04.425+0000] {subprocess.py:94} INFO - [0m03:05:04  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-03-16T03:05:05.585+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-03-16T03:05:05.595+0000] {local.py:138} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v11.json is above dbt-ol supported version 7. This might cause errors.
[2024-03-16T03:05:05.598+0000] {local.py:252} INFO - Inlets: [Dataset(uri='postgres://mydb:5432/postgres.dbt_gai.my_first_dbt_model', extra=None)]
[2024-03-16T03:05:05.599+0000] {local.py:253} INFO - Outlets: [Dataset(uri='postgres://mydb:5432/postgres.dbt_gai.my_second_dbt_model', extra=None)]
[2024-03-16T03:05:05.599+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-03-16T03:05:05.621+0000] {dag.py:3820} INFO - Setting next_dagrun for weather_dbt_dag to 2024-03-16T00:00:00+00:00, run_after=2024-03-17T00:00:00+00:00
[2024-03-16T03:05:05.652+0000] {local.py:371} INFO - [0m03:05:04  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-03-16T03:05:05.654+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/models/baseoperator.py:1476 RemovedInAirflow3Warning: Passing 'execution_date' to 'TaskInstance.xcom_push()' is deprecated.
[2024-03-16T03:05:05.691+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=weather_dbt_dag, task_id=my_second_dbt_model.run, execution_date=20240315T000000, start_date=20240316T030459, end_date=20240316T030505
[2024-03-16T03:05:05.728+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-16T03:05:05.745+0000] {taskinstance.py:3281} INFO - 1 downstream tasks scheduled from follow-on schedule check
