[2024-02-10T06:00:03.140+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_api_dag.load_data_to_postgres scheduled__2024-02-10T05:00:00+00:00 [queued]>
[2024-02-10T06:00:03.150+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_api_dag.load_data_to_postgres scheduled__2024-02-10T05:00:00+00:00 [queued]>
[2024-02-10T06:00:03.151+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-02-10T06:00:03.170+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): load_data_to_postgres> on 2024-02-10 05:00:00+00:00
[2024-02-10T06:00:03.178+0000] {standard_task_runner.py:60} INFO - Started process 15762 to run task
[2024-02-10T06:00:03.184+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'weather_api_dag', 'load_data_to_postgres', 'scheduled__2024-02-10T05:00:00+00:00', '--job-id', '425', '--raw', '--subdir', 'DAGS_FOLDER/weather_api__dag.py', '--cfg-path', '/tmp/tmp34fdcnk0']
[2024-02-10T06:00:03.187+0000] {standard_task_runner.py:88} INFO - Job 425: Subtask load_data_to_postgres
[2024-02-10T06:00:03.252+0000] {task_command.py:423} INFO - Running <TaskInstance: weather_api_dag.load_data_to_postgres scheduled__2024-02-10T05:00:00+00:00 [running]> on host c5d03f501d38
[2024-02-10T06:00:03.402+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='ahaonezero@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_api_dag' AIRFLOW_CTX_TASK_ID='load_data_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-02-10T05:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-10T05:00:00+00:00'
[2024-02-10T06:00:03.417+0000] {logging_mixin.py:188} INFO - /opt/***/dags/weather_data2024-02-10T05:00:00+00:00.json
[2024-02-10T06:00:03.432+0000] {base.py:83} INFO - Using connection ID 'my_***_conn' for task execution.
[2024-02-10T06:00:03.451+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-02-10T06:00:03.461+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=weather_api_dag, task_id=load_data_to_***, execution_date=20240210T050000, start_date=20240210T060003, end_date=20240210T060003
[2024-02-10T06:00:03.518+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-10T06:00:03.552+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
